#!/usr/bin/env bash
# Script: 0-world_wide_web
# This script displays information about subdomains for a given domain.

display_info() {
    local domain=$1
    local subdomain=$2
    local destination=$3

    record_type=$(dig "$subdomain.$domain" +short | head -n1)
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    # When only the parameter domain is provided
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    # When passing domain and subdomain parameters
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    result=$(dig "$sub.$domain" +short)
    if [ -n "$result" ]; then
        display_info "$domain" "$sub" "$result"
    fi
done
