#!/usr/bin/env bash
# Script: 0-world_wide_web
# This script displays information about subdomains for a given domain.

display_info() {
    local domain=$1
    local subdomain=$2
    local record_type=$3
    local destination=$4
    local expected_ip=$5

    if [ "$destination" == "$expected_ip" ]; then
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "Warning: The subdomain $subdomain is a $record_type record but points to $destination instead of the expected $expected_ip"
    fi
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    # When only the parameter domain is provided
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    # When passing domain and subdomain parameters
    subdomains=("$subdomain")
fi

# Define the expected IP addresses for each subdomain
declare -A expected_ips
expected_ips=([www]="lb-01-expected-ip" [lb-01]="lb-01-expected-ip" [web-01]="web-01-expected-ip" [web-02]="web-02-expected-ip")

for sub in "${subdomains[@]}"; do
    result=$(dig "$sub.$domain" +short)
    if [ -n "$result" ]; then
        record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/{getline; print $4}')
        display_info "$domain" "$sub" "$record_type" "$result" "${expected_ips[$sub]}"
    fi
done

