#!/usr/bin/env bash
#this script configure haproxy and add ssl certificate

SUBDOMAIN="www.yaqscotech.tech"
WEB_SERVER_1_IP="35.153.33.61"
WEB_SERVER_1_PORT="80"
WEB_SERVER_2_IP="54.165.26.200"
WEB_SERVER_2_PORT="80"

# Install HAProxy and Certbot
sudo apt update
sudo apt install -y haproxy
sudo apt-get install -y certbot

# Stop HAProxy
sudo service haproxy stop

# Obtain SSL certificate using Certbot
sudo certbot certonly --standalone -d $SUBDOMAIN

sudo mkdir -p /etc/haproxy/certs
DOMAIN='www.yaqscotech.tech' sudo -E bash -c 'cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem /etc/letsencrypt/live/$DOMAIN/privkey.pem > /etc/haproxy/certs/$DOMAIN.pem'

# Change the mode of the private key file
sudo chmod -R go-rwx /etc/haproxy/certs

# Configure HAProxy for SSL termination
frontend_config="\
frontend my_frontend\n\
        bind *:80
        bind *:443 ssl crt /etc/haproxy/certs/www.yaqscotech.tech.pem\n\
        redirect scheme https code 302 if !{ ssl_fc }\n\
        default_backend my_backend\n\
"


backend_config="\
backend my_backend\n\
        balance roundrobin\n\
        server web-server-1 $WEB_SERVER_1_IP:$WEB_SERVER_1_PORT check\n\
        server web-server-2 $WEB_SERVER_2_IP:$WEB_SERVER_2_PORT check\n\
"
echo -e "\n$frontend_config\n$backend_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy start
