#!/usr/bin/env bash
# This script transfers a file to a server using scp

FILE_PATH="$1"
SERVER_IP="$2"
SSH_USERNAME="$3"
SSH_KEY_PATH="$4"

if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
elif [ $# -lt 4 ]; then
    ssh ubuntu@100.26.213.11 -i /home/abu/.ssh/id_rsa 'ls ~/'
else
    scp "$SSH_KEY_PATH" $SCP_OPTS "$FILE_PATH" "$SSH_USERNAME@$SERVER_IP":~/
fi
