#!/usr/bin/env bash
# redirection configuration

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

placed="server_name localhost;\n\trewrite ^\/redirect_me https:\/\/https://www.youtube.com/watch?v=7YqlP7HYU1g 301;"
sudo sed -i "s/server_name localhost;/$placed/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
