#!/usr/bin/env bash
# redirection configuration

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a custom Nginx configuration file for the 404 page and redirection
sudo tee /etc/nginx/sites-available/mysite << EOF
server {
    listen 80 default_server;
    root /var/www/html;
    index index.html index.html index.nginx-debian.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF
#echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Enable the custom configuration file by creating a symbolic link
sudo ln -sf /etc/nginx/sites-available/mysite /etc/nginx/sites-enabled/

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart

