#!/usr/bin/env bash
# This script cofigures a ngnix server to serve Hello World! AND redirect to a site

# Update the package repository and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a custom Nginx configuration file for both "Hello World!" and redirection
sudo cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 "Hello World!\n";
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Create symbolic links to enable the new configuration
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx to apply the new configuration
sudo systemctl restart nginx

echo "Nginx configured for serving 'Hello World!' and redirection."

