#!/usr/bin/env bash
# Custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx

# Create a custom Nginx configuration file for the 404 page
cat << EOF | sudo tee /etc/nginx/sites-available/custom_404 > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }

    location / {
        return 404 "Ceci n'est pas une page\n";
    }
}
EOF

sudo ln -sf /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Restart Nginx to apply the new configuration
sudo service nginx restart

