#!/usr/bin/env bash
# This script configures a brand new machine with a specific header

sudo apt-get -y update
sudo apt-get -y install nginx

cat <<EOF | sudo tee /etc/nginx/sites-available/custom_header
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location /custom_header {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        add_header X-Served-By "\$HOSTNAME";
        return 200 "Hello World!\n";
    }
}
EOF
sudo ln -sf /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/
sudo nginx -t
sudo service nginx restart

