#!/usr/bin/env bash
# this script configures haproxy to serve two webserver

apt-get update
apt-get install -y haproxy

frontend_config="\
frontend my_frontend\n\
    	bind *:80\n\
    	mode http\n\
    	default_backend my_backend\n\
"

backend_config="\
backend my_backend\n\
    	mode http\n\
    	balance roundrobin\n\
    	server 332685-web-01 35.153.33.61:80 check\n\
    	server 332685-web-02 54.165.26.200:80 check\n\
"

echo -e "\n$frontend_config\n$backend_config" | tee -a /etc/haproxy/haproxy.cfg > /dev/null

service haproxy restart
