#!/usr/bin/env bash
# this script implement load balancer

# Update the server
sudo apt-get -y update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 100.26.213.11:80 check
    server web-02 54.237.35.11:80 check
EOF

# Start HAProxy
sudo service haproxy start

# Enable HAProxy to start on boot
sudo update-rc.d haproxy defaults

echo "HAProxy installed and configured successfully!"

