#!/usr/bin/env bash
# Configures Nginx to listen on port 80 for all active IPv4 IPs
service nginx start
sed -i '/listen 80 default_server;/a listen 80 default_server ipv4only=on;' /etc/nginx/sites-enabled/default
service nginx restart

