#!/usr/bin/env bash
# Bash script to fix Nginx not listening on port 80
if ! service nginx status > /dev/null 2>&1; then
    service nginx start
fi
echo "listen 80 ipv4only=on" >> /etc/nginx/sites-enabled/default
service nginx restart
