#!/usr/bin/env bash
# this script stops the 4-to_infinity_and_beyond process

PID=$(pgrep -x "4-to_infinity_and_beyond.sh")
if [ -n "$PID" ]; then
	echo "Stopping 4-to_infinity_and_beyond process (PID: $PID)"
	kill -2 "$PID"
else
	echo "4-to_infinity_and_beyond process is not running."
fi
