#!/usr/bin/env bash
# this script stops the 4-to_infinity_and_beyond process gracefully

sigint_handler() {
	echo "Stopping 4-to_infinity_and_beyond process gracefully..."
	exit 0
}

trap sigint_handler SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
