#!/bin/bash

sed -i '/^#net\/ipv4\/ip_forward=1/s/^#//' /etc/ufw/sysctl.conf

# Modify UFW configuration to enable port forwarding
sh -c 'echo "*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT" >> /etc/ufw/before.rules'

# Reload UFW
ufw reload

# Display UFW status
ufw status
