#!/usr/bin/env bash
# This script fixes the Apache configuration to serve content from the root directory

if ! pgrep apache2 > /dev/null; then
    service apache2 start
fi

apache_config="/etc/apache2/sites-available/000-default.conf"

if grep -q "DocumentRoot /var/www/html" "$apache_config"; then
    :
else
    sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html\n|' "$apache_config"
    service apache2 restart
fi
