#!/usr/bin/env bash
# make your fix short and sweet
sed -i 's/user\s*nginx;/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
